#!/bin/bash

# tailscaleのDNS設定がリセットされる問題を解決する最終手段

cat << END > /etc/resolv.conf
nameserver 192.168.10.1

# resolv.conf(5) file generated by tailscale
# For more info, see https://tailscale.com/s/resolvconf-overwrite
# DO NOT EDIT THIS FILE BY HAND -- CHANGES WILL BE OVERWRITTEN

nameserver 100.100.100.100
search tayra-buri.ts.net
END